arch: 
  - arm64
language: node_js
node_js: 
  - 14.16
before_script: 
  - "npm install"
script: "true"
after_script: []
before_install: []
install: []
after_install: []
build: 
  - npm start
after_script: 
  - "echo done"
after_success: []
after_failure: []
before_deploy: []
deploy:
  - provider: codedeploy
    revision_type: github
    application: "BatMan"
    deployment_group: "BatManGroup"
    region: "us-west-1c"
